server:
  servlet:
    context-path: /api
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    web: info
